project_id = "gclbltatkbwbqxqqrcea"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-ceo-otp]
verify_jwt = true

[functions.verify-ceo-otp]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.get-onesignal-app-id]
verify_jwt = false

[functions.notify-managers-new-order]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false

[functions.assistant-chat]
verify_jwt = false

[functions.parse-excel-report]
verify_jwt = true

[functions.moderate-image]
verify_jwt = true
