project_id = "gclbltatkbwbqxqqrcea"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.get-onesignal-app-id]
verify_jwt = false
